name: Accept Package

on:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: write  

jobs:
  accept_package:
    runs-on: ubuntu-latest

    # Only run if the label added is "package accepted"
    if: ${{ github.event.label.name == 'package accepted' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Ensure SQLite is available
        run: python -c "import sqlite3; print(sqlite3.sqlite_version)"

      - name: Ensure git is installed
        run: git --version

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          eval "$(ssh-agent -s)"
          echo "${{ secrets.GITOLITE_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519_bioc_ci
          chmod 600 ~/.ssh/id_ed25519_bioc_ci
          ssh-add ~/.ssh/id_ed25519_bioc_ci

          ssh-keyscan -H git.bioconductor.org >> ~/.ssh/known_hosts

          cat > ~/.ssh/config <<EOF
          Host git.bioconductor.org
            IdentityFile ~/.ssh/id_ed25519_bioc_ci
            IdentitiesOnly yes
          EOF

      - name: Accept Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BIOC_ORG_TOKEN: ${{ secrets.BIOC_ORG_TOKEN }}
          ORG_NAME: Bioconductor
          TEAM_SLUG: packagereviewers    # GitHub team slug, always lowercase
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          BIOC_STAGING_TOKEN: ${{ secrets.BIOC_STAGING_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          SPB_RUNIVERSE: biocstaging
          BIOC_STAGING_ORG: BiocStaging
          GITOLITE_ADMIN_REPO: ${{ secrets.GITOLITE_ADMIN_REPO }}
          MANIFEST_REPO: ${{ secrets.MANIFEST_REPO }}
          DATACITE_USERNAME: ${{ secrets.DATACITE_USERNAME }}
          DATACITE_PASSWORD: ${{ secrets.DATACITE_PASSWORD }}
          DATACITE_TESTING_USERNAME: ${{ secrets.DATACITE_TESTING_USERNAME }}
          DATACITE_TESTING_PASSWORD: ${{ secrets.DATACITE_TESTING_PASSWORD }}
          BIOC_CREDENTIALS_USER: ${{ secrets.BIOC_CREDENTIALS_USER }}
          BIOC_CREDENTIALS_PASSWORD: ${{ secrets.BIOC_CREDENTIALS_PASSWORD }}
          BIOC_PKG_HOSTING_ORG: bioconductor-source
          BIOC_PKG_HOSTING_TOKEN: ${{ secrets.BIOC_PKG_HOSTING_TOKEN }}
        run: python scripts/accept_package.py

